"""
rag_pageindex.py — Vectorless RAG using PageIndex-style LLM tree navigation

Implements the core concept from VectifyAI/PageIndex:
  https://github.com/VectifyAI/PageIndex

Architecture
------------
1. Index     Documents are grouped by source URL into "pages".
             Each page gets a one-line summary generated by GPT-4o-mini (cached
             to .pageindex_cache.json — only rebuilt if the corpus changes).
             No vector embeddings are used at any stage.

2. Navigate  At query time, GPT-4o-mini reads the full page-summary index and
             selects the most relevant pages through language reasoning, not
             cosine similarity.

3. Retrieve  All chunks from the selected pages are returned as context.

4. Answer    Groq llama-3.1-8b-instant generates the final answer — the same
             model used by the other pipelines for a fair comparison.

What is deliberately left out (unlike rag.py):
  - No vector embeddings or cosine similarity at retrieval time
  - No BM25 keyword matching
  - No cross-encoder reranking
  - No multi-query expansion
  - Selection is driven entirely by LLM reasoning over text summaries
"""

import os
import re
import json
from collections import defaultdict
from dotenv import load_dotenv
from langchain_chroma import Chroma
from langchain_core.documents import Document
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser
from langchain_groq import ChatGroq
from openai import OpenAI
from embeddings import NomicEmbeddings

load_dotenv()

CHROMA_PATH      = "./chroma_python_docs"
GROQ_MODEL       = "llama-3.1-8b-instant"
OPENAI_NAV_MODEL = "gpt-4o-mini"   # navigation only — GPT-4o-mini matches PageIndex's LLM usage
CACHE_PATH       = ".pageindex_cache.json"
TOP_PAGES        = 1                # single most relevant page selected by LLM reasoning


# ---------------------------------------------------------------------------
# Index building
# ---------------------------------------------------------------------------

def _generate_page_summary(url: str, content_preview: str, client: OpenAI) -> str:
    """Ask GPT to produce a one-line description of a documentation page."""
    prompt = (
        "In one short sentence (max 20 words), describe what Python topic "
        "this documentation page covers.\n"
        f"URL: {url}\n"
        f"Content preview: {content_preview[:400]}\n"
        "Summary:"
    )
    try:
        resp = client.chat.completions.create(
            model=OPENAI_NAV_MODEL,
            messages=[{"role": "user", "content": prompt}],
            max_tokens=50,
            temperature=0,
        )
        return resp.choices[0].message.content.strip()
    except Exception:
        # Graceful fallback: derive a label from the URL slug
        return url.split("/")[-1].replace(".html", "").replace("-", " ")


def _load_or_build_index(page_to_chunks: dict, client: OpenAI) -> dict:
    """
    Return {url: summary} mapping.
    Load from cache if the corpus fingerprint matches; otherwise rebuild via OpenAI.
    """
    urls = sorted(page_to_chunks.keys())
    fingerprint = str(hash(tuple(urls)))

    if os.path.exists(CACHE_PATH):
        with open(CACHE_PATH) as f:
            cache = json.load(f)
        if cache.get("fingerprint") == fingerprint:
            return cache["index"]

    print("  Building PageIndex summaries via OpenAI (first run only)...")
    index = {}
    for url, chunks in page_to_chunks.items():
        preview = " ".join(c.page_content for c in chunks[:2])
        summary = _generate_page_summary(url, preview, client)
        index[url] = summary
        print(f"    ✓ {url.split('/')[-1]}: {summary}")

    with open(CACHE_PATH, "w") as f:
        json.dump({"fingerprint": fingerprint, "index": index}, f, indent=2)

    return index


# ---------------------------------------------------------------------------
# Navigation
# ---------------------------------------------------------------------------

def _navigate(question: str, index: dict, client: OpenAI) -> list[str]:
    """
    Present all page summaries to GPT and ask it to select the most relevant
    pages by reasoning — no embeddings, pure language understanding.
    """
    entries = "\n".join(
        f"[{i + 1}] {url.split('/')[-1]} — {summary}"
        for i, (url, summary) in enumerate(index.items())
    )
    prompt = (
        f"You are a precise document navigator for Python documentation.\n"
        f"Given the page index below, select the {TOP_PAGES} pages most likely to "
        f"contain a direct, complete answer to the question.\n\n"
        f"Rules:\n"
        f"- Prefer the most specific page over a general one "
        f"(e.g. 'itertools.html' over 'tutorial/index.html' for an itertools question).\n"
        f"- If the question mentions a specific function or module, prioritise the page "
        f"dedicated to that module.\n"
        f"- Only select a second page if the question clearly spans two topics.\n\n"
        f"Page Index:\n{entries}\n\n"
        f"Question: {question}\n\n"
        f"Reply with only the page numbers, comma-separated (e.g. '3, 7')."
    )
    try:
        resp = client.chat.completions.create(
            model=OPENAI_NAV_MODEL,
            messages=[{"role": "user", "content": prompt}],
            max_tokens=20,
            temperature=0,
        )
        raw = resp.choices[0].message.content.strip()
        numbers = [int(n) - 1 for n in re.findall(r"\d+", raw)]
        urls = list(index.keys())
        return [urls[n] for n in numbers if 0 <= n < len(urls)]
    except Exception:
        return list(index.keys())[:TOP_PAGES]


# ---------------------------------------------------------------------------
# Retriever factory
# ---------------------------------------------------------------------------

def load_pageindex_retriever():
    embeddings = NomicEmbeddings()
    vectorstore = Chroma(persist_directory=CHROMA_PATH, embedding_function=embeddings)
    client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))

    raw = vectorstore.get()
    page_to_chunks: dict[str, list[Document]] = defaultdict(list)
    for pc, m in zip(raw["documents"], raw["metadatas"]):
        src = m.get("source", "unknown")
        page_to_chunks[src].append(Document(page_content=pc, metadata=m))

    index = _load_or_build_index(page_to_chunks, client)

    def retrieve(query: str) -> list[Document]:
        selected_urls = _navigate(query, index, client)
        docs, seen = [], set()
        for url in selected_urls:
            for doc in page_to_chunks.get(url, []):
                key = hash(doc.page_content)
                if key not in seen:
                    seen.add(key)
                    docs.append(doc)
        return docs

    return retrieve


# ---------------------------------------------------------------------------
# Pipeline
# ---------------------------------------------------------------------------

def build_qa_chain():
    llm = ChatGroq(model=GROQ_MODEL, temperature=0)
    retrieve = load_pageindex_retriever()

    prompt = ChatPromptTemplate.from_template(
        "You are a Python documentation assistant. "
        "Answer the question using ONLY the information in the context below. "
        "Do not use any knowledge outside of the provided context. "
        "Do not cite or reference the context — just answer directly. "
        "If the answer is not in the context, say: "
        "\"I couldn't find this in the Python docs.\"\n\n"
        "Use Markdown. Wrap code in ```python blocks.\n\n"
        "Context:\n{context}\n\n"
        "Question: {question}\n\n"
        "Answer:"
    )

    def format_docs(docs: list[Document]) -> str:
        return "\n\n".join(
            f"[Source: {doc.metadata.get('source', 'unknown')}]\n{doc.page_content}"
            for doc in docs
        )

    class PageIndexPipeline:
        def invoke(self, input_dict: dict) -> dict:
            question = input_dict["question"]
            docs = retrieve(question)
            prompt_value = prompt.invoke({
                "context": format_docs(docs),
                "question": question,
            })
            answer = StrOutputParser().invoke(llm.invoke(prompt_value))
            return {"answer": answer, "source_docs": docs}

        def stream(self, question: str, chat_history: list = None):
            docs = retrieve(question)
            prompt_value = prompt.invoke({
                "context": format_docs(docs),
                "question": question,
            })
            token_stream = (chunk.content for chunk in llm.stream(prompt_value))
            return docs, token_stream

    return PageIndexPipeline()


def ask(pipeline, question: str, chat_history: list = None) -> dict:
    result = pipeline.invoke({"question": question, "chat_history": chat_history or []})
    return {
        "answer": result["answer"],
        "sources": [doc.metadata.get("source", "unknown") for doc in result["source_docs"]],
    }